package yage.graphics.fw

import org.lwjgl.glfw.GLFW.*

object Key:

  def apply(i: Int) = Key.values.find(_.id == i).get

enum Key(val id: Int):

  case K_0 extends Key(GLFW_KEY_0)
  case K_1 extends Key(GLFW_KEY_1)
  case K_2 extends Key(GLFW_KEY_2)
  case K_3 extends Key(GLFW_KEY_3)
  case K_4 extends Key(GLFW_KEY_4)
  case K_5 extends Key(GLFW_KEY_5)
  case K_6 extends Key(GLFW_KEY_6)
  case K_7 extends Key(GLFW_KEY_7)
  case K_8 extends Key(GLFW_KEY_8)
  case K_9 extends Key(GLFW_KEY_9)
  case F1 extends Key(GLFW_KEY_F1)
  case F2 extends Key(GLFW_KEY_F2)
  case F3 extends Key(GLFW_KEY_F3)
  case F4 extends Key(GLFW_KEY_F4)
  case F5 extends Key(GLFW_KEY_F5)
  case F6 extends Key(GLFW_KEY_F6)
  case F7 extends Key(GLFW_KEY_F7)
  case F8 extends Key(GLFW_KEY_F8)
  case F9 extends Key(GLFW_KEY_F9)
  case F10 extends Key(GLFW_KEY_F10)
  case F11 extends Key(GLFW_KEY_F11)
  case F12 extends Key(GLFW_KEY_F12)
  case A extends Key(GLFW_KEY_A)
  case B extends Key(GLFW_KEY_B)
  case C extends Key(GLFW_KEY_C)
  case Comma extends Key(GLFW_KEY_COMMA)
  case D extends Key(GLFW_KEY_D)
  case Delete extends Key(GLFW_KEY_DELETE)
  case Down extends Key(GLFW_KEY_DOWN)
  case E extends Key(GLFW_KEY_E)
  case End extends Key(GLFW_KEY_END)
  case Enter extends Key(GLFW_KEY_ENTER)
  case Equal extends Key(GLFW_KEY_EQUAL)
  case Escape extends Key(GLFW_KEY_ESCAPE)
  case F extends Key(GLFW_KEY_F)
  case G extends Key(GLFW_KEY_G)
  case H extends Key(GLFW_KEY_H)
  case Home extends Key(GLFW_KEY_HOME)
  case I extends Key(GLFW_KEY_I)
  case Insert extends Key(GLFW_KEY_INSERT)
  case J extends Key(GLFW_KEY_J)
  case K extends Key(GLFW_KEY_K)
  case L extends Key(GLFW_KEY_L)
  case Last extends Key(GLFW_KEY_LAST)
  case Left extends Key(GLFW_KEY_LEFT)
  case LeftAlt extends Key(GLFW_KEY_LEFT_ALT)
  case LeftBracket extends Key(GLFW_KEY_LEFT_BRACKET)
  case LeftControl extends Key(GLFW_KEY_LEFT_CONTROL)
  case LeftShift extends Key(GLFW_KEY_LEFT_SHIFT)
  case LeftSuper extends Key(GLFW_KEY_LEFT_SUPER)
  case M extends Key(GLFW_KEY_M)
  case Menu extends Key(GLFW_KEY_MENU)
  case Minus extends Key(GLFW_KEY_MINUS)
  case N extends Key(GLFW_KEY_N)
  case NumLock extends Key(GLFW_KEY_NUM_LOCK)
  case O extends Key(GLFW_KEY_O)
  case P extends Key(GLFW_KEY_P)
  case PageDown extends Key(GLFW_KEY_PAGE_DOWN)
  case PageUp extends Key(GLFW_KEY_PAGE_UP)
  case Pause extends Key(GLFW_KEY_PAUSE)
  case Period extends Key(GLFW_KEY_PERIOD)
  case PrintScreen extends Key(GLFW_KEY_PRINT_SCREEN)
  case Q extends Key(GLFW_KEY_Q)
  case R extends Key(GLFW_KEY_R)
  case Right extends Key(GLFW_KEY_RIGHT)
  case RightAlt extends Key(GLFW_KEY_RIGHT_ALT)
  case RightBracker extends Key(GLFW_KEY_RIGHT_BRACKET)
  case RightControl extends Key(GLFW_KEY_RIGHT_CONTROL)
  case RightShift extends Key(GLFW_KEY_RIGHT_SHIFT)
  case RightSuper extends Key(GLFW_KEY_RIGHT_SUPER)
  case S extends Key(GLFW_KEY_S)
  case ScrollLock extends Key(GLFW_KEY_SCROLL_LOCK)
  case Semicolon extends Key(GLFW_KEY_SEMICOLON)
  case Slash extends Key(GLFW_KEY_SLASH)
  case Space extends Key(GLFW_KEY_SPACE)
  case T extends Key(GLFW_KEY_T)
  case Tab extends Key(GLFW_KEY_TAB)
  case U extends Key(GLFW_KEY_U)
  case Unknown extends Key(GLFW_KEY_UNKNOWN)
  case Up extends Key(GLFW_KEY_UP)
  case V extends Key(GLFW_KEY_V)
  case W extends Key(GLFW_KEY_W)
  case World1 extends Key(GLFW_KEY_WORLD_1)
  case World2 extends Key(GLFW_KEY_WORLD_2)
  case X extends Key(GLFW_KEY_X)
  case Y extends Key(GLFW_KEY_Z) // !!!
  case Z extends Key(GLFW_KEY_Y) // !!!
